version: '3.3'

services:
  core-php:
    image: devilbox/php-fpm:8.2-work
    container_name: core-php
    expose:
      - "9000"
    working_dir: /var/www/application
    volumes:
      - ../application:/var/www/application
      - ./global/services/supervisor/conf.d/:/etc/supervisor/conf.d/
    restart: 'no'
    command:
      - "supervisord"

  core-server:
    image: caddy:2.7-alpine
    container_name: core-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../application:/var/www/application
    restart: "on-failure"

  core-db:
    image: mysql:latest
    container_name: core-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tg_setup
      MYSQL_USER: tg_setup_user
      MYSQL_PASSWORD: "!tg_53tup_pa55word!"

  core-redis:
    image: bitnami/redis
    container_name: core-redis
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  core-ngrok:
    image: ngrok/ngrok
    container_name: core-ngrok
    ports:
      - "4040:4040"
    volumes:
      - ./global/services/ngrok/config.yml:/etc/config.yml

  core-telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: core-telegram-bot-api
    ports:
      - "8081:8081"
      - "8082:8082"
    env_file:
      - ./.env
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_STAT: ${TELEGRAM_STAT:-0}
      TELEGRAM_MAX_WEBHOOK_CONNECTIONS: ${TELEGRAM_MAX_WEBHOOK_CONNECTIONS:-100}
      TELEGRAM_MAX_CONNECTIONS: ${TELEGRAM_MAX_CONNECTIONS:-100}
      TELEGRAM_LOCAL: ${TELEGRAM_LOCAL:-1}